openapi: 3.1.0
info:
  title: admin-http-api
  version: '1.0'
  summary: The Precog admin HTTP REST API.
  description: The Precog admin HTTP REST API.
  contact:
    url: 'https://precog.com'
    email: support@precog.com
servers:
  - url: 'http://localhost:30000'
security:
  - BearerAuth: []
paths:
  /admin/tenants/{tenant-id}/pipelines/{pipeline-id}/actionRequired:
    parameters:
      - schema:
          type: string
        name: tenant-id
        in: path
        required: true
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    post:
      summary: Transition specified dataset statuses of a pipeline to "action required"
      tags: []
      operationId: action-required
      responses:
        '204':
          description: Status of primary dataset has been transitioned successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Transition a dataset status to "action required" (error).
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/action-required'
  /admin/tenants/{tenant-id}/pipelines/{pipeline-id}/datasets/{dataset-id}/rediscover:
    parameters:
      - schema:
          type: string
        name: tenant-id
        in: path
        required: true
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
      - schema:
          type: string
        name: dataset-id
        in: path
        required: true
    post:
      summary: Transition specified dataset status of a pipeline to "accepted"
      tags: []
      operationId: rediscover
      responses:
        '204':
          description: Status of dataset has been transitioned successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
        '422':
          description: Semantic error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
      description: Transition a dataset status to "accepted".

components:
  schemas:
    action-required:
      description: ''
      type: object
      title: ''
      properties: 
        primaryDataset:
          type: string
          minLength: 1
        secondaryDatasets:
          type: array
          uniqueItems: true
          items:  
            type: string
        message:
          type: string
          minLength: 1
        required:
          - primaryDataset
          - message
    error-message:
      title: error-message
      type: object
      properties:
        error:
          type: object
          required:
            - type
            - details
          properties:
            type:
              type: string
              minLength: 1
            details:
              type: string
      required:
        - error
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
