openapi: 3.1.0
info:
  title: metadata-http-api
  version: '1.0'
  summary: The Precog metadata HTTP REST API.
  description: The Precog metadata HTTP REST API.
  contact:
    url: 'https://precog.com'
    email: support@precog.com
servers:
  - url: 'http://localhost:30000'
security:
  - BearerAuth: []
paths:
  '/pipelines/{pipeline-id}/metadata':
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
    get:
      summary: Get metadata related to this pipeline
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pipeline-metadata'
              examples:
                example-1:
                  value:
                    metadata:
                      - datasetId: '133425/example'
                        tables:
                          - tableName: example
                            primaryKey: [ id ]
                            columns:
                              - columnName: id
                                columnType: string
                                maxObservedStringLength: 42
                              - columnName: foo
                                columnType: decimal
                          - tableName: example_items
                            primaryKey: [ id_example, array_index ]
                            foreignKeys: 
                              example: 
                                - local: [ id_example ]
                                - reference: [ id ]
                            columns:
                              - columnName: id_example
                                columnType: string
                                maxObservedStringLength: 42
                              - columnName: array_index
                                columnType: long
                              - columnName: bar
                                columnType: boolean
        '401':
          description: Unauthorized
        '404':
          description: Pipeline not found.
      operationId: get-pipelines-pipeline-id-metadata
      description: Get metadata for a particular particular pipeline.
  '/sources/{source-id}/dataset-properties':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    get:
      summary: Get dataset properties related to the in-band datasets present in this source
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/source-dataset-properties'
              examples:
                example-1:
                  value:
                    sourceId: a864cb9a-7be2-11f0-aa5e-2a65c4d820c0
                    datasetProperties:
                      - name: 70c7b714-7be3-11f0-a48c-2a65c4d820c0:/Question Bank
                        properties:
                          - primaryKey:
                              type: strict
                              components:
                                - $.data.results[:_].questionId
                                - $.data.results[:_].questionBankId
                      - name: 70c7b714-7be3-11f0-a48c-2a65c4d820c0:/Survey Categories
                        properties:
                          - primaryKey:
                              type: strict
                              components:
                                - $.data.results[:_].surveyCategoryId
                                - $.data.results[:_].surveyId
                      - name: 70c7b714-7be3-11f0-a48c-2a65c4d820c0:/Survey Templates
                        properties:
                          - primaryKey:
                              type: strict
                              components:
                                - $.data.results[:_].surveyTemplateId
                                - $.data.results[:_].surveyId
                                - $.data.results[:_].id
                      - name: 70c7b714-7be3-11f0-a48c-2a65c4d820c0:/Surveys
                        properties:
                          - primaryKey:
                              type: strict
                              components:
                                - $.data.id
        '422':
          description: Returned when the source does not have any in-band datasets
        '401':
          description: Unauthorized
        '404':
          description: Source not found.
      operationId: get-source-id-dataset-properties
      description: Get dataset properties for datasets in a particular source.
components:
  schemas:
    pipeline-metadata:
      description: 'Tables in this pipeline'
      type: object
      title: 'Pipeline metadata'
      properties:
        metadata:
          type: array
          title: 'Datasets'
          items:
            $ref: '#/components/schemas/dataset-metadata'
    dataset-metadata:
      description: 'Dataset tables'
      type: object
      title: 'Dataset tables'
      properties:
        datasetId:
          type: string
          minLength: 1
        tables:
          type: array
          title: 'Datasets'
          items:
            $ref: '#/components/schemas/table'
    table:
      description: 'Table schema'
      type: object
      title: 'Table schema'
      properties:
        tableName:
          type: string
          minLength: 1
        primaryKey:
          type: array
          uniqueItems: true
          items:
            type: string
        foreignKeys:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/foreignKey'
        columns:
          type: array
          title: 'Columns'
          items:
            $ref: '#/components/schemas/column'
    foreignKey:
      description: 'Foreign key'
      type: object
      required:
        - local
        - reference
      properties:
        local:
          type: array
          items: string
          minLength: 1
        reference:
          type: array
          items: string
          minLength: 1
    column:
      description: 'Column'
      type: object
      title: 'Column'
      required:
        - columnName
        - columnType
      properties:
        columnName:
          type: string
          minLength: 1
        columnType:
          type:
            oneOf:
              - properties: {}
                enum:
                  - boolean
                  - long
                  - double
                  - decimal
                  - localTime
                  - localDatetime
                  - localDate
                  - offsetDatetime
                  - string
        maxObservedStringLength:
          type: integer
    source-dataset-properties:
      description: 'Datasets properties used in the in-band datasets in this source'
      type: object
      title: 'Source datasets properties'
      properties:
        sourceId:
          type: string
        datasetProperties:
          type: array
          title: 'Datasets properties'
          items:
            $ref: '#/components/schemas/dataset-properties'
    dataset-properties:
      description: 'Dataset properties for a particular dataset in a source'
      type: object
      title: 'Source dataset properties'
      properties:
        name:
          type: string
          minLength: 1
        properties:
          type: array
          title: 'Dataset properties'
          items:
            $ref: '#/components/schemas/dataset-property'
    dataset-property:
      description: One dataset property for a given dataset in a given source
      oneOf:
        - $ref: '#/components/schemas/primary-key-property'
    primary-key-property:
      description: Primary key for a given dataset
      type: object
      title: Source dataset properties
      properties:
        primaryKey:
          type: object
          description: A primary key property
          properties:
            type:
              oneOf:
                - type: string
                  enum: [strict, optional]
                  description: Indicates whether the key is strict or optional
            components:
              type: array
              title: Primary key components
              items:
                type: string
                minLength: 1
          required: [type, components]
      required: [primaryKey]
      additionalProperties: false

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
