openapi: 3.1.0
info:
  title: public-http-api
  version: '1.0'
  summary: The Precog public HTTP REST API.
  description: The Precog public HTTP REST API.
  contact:
    url: 'https://precog.com'
    email: support@precog.com
servers:
  - url: 'http://localhost:3000'
paths:
  /sources:
    get:
      summary: Get Sources
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plugin-definition'
      operationId: get-sources
      description: Retrieve the configured sources.
    post:
      summary: Create Source
      tags: []
      operationId: post-sources
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plugin-definition'
        '400':
          description: Request body malformed.
        '415':
          description: Source kind unsupported. <or> Source version unsupported.
      description: Configure a new source.
  '/sources/{source-id}':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    get:
      summary: Get a source
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plugin-definition'
        '404':
          description: Source not found.
      operationId: get-sources-source-id
      description: Get a particular source.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    post:
      summary: Replace a source config
      tags: []
      operationId: post-sources-source-id
      responses:
        '204':
          description: No Content
        '400':
          description: Request body malformed.
        '404':
          description: Source not found.
      description: Replace a source configuration for a particular source.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plugin-definition'
  /destinations:
    get:
      summary: Get Destinations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plugin-definition'
      operationId: get-destinations
      description: Retrieve the configured destinations.
    post:
      summary: Create Destination
      tags: []
      operationId: post-destinations
      responses:
        '200':
          description: OK
        '400':
          description: Request body malformed.
        '415':
          description: Destination kind unsupported. <or> Destination version unsupported.
      description: Configure a new destination.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plugin-definition'
  '/destinations/{destination-id}':
    parameters:
      - schema:
          type: string
        name: destination-id
        in: path
        required: true
    get:
      summary: Get a destination
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plugin-definition'
        '404':
          description: Destination not found.
      operationId: get-destinations-destination-id
      description: Get a particular destination.
    post:
      summary: Replace a destination config
      tags: []
      operationId: post-destinations-destination-id
      responses:
        '204':
          description: No Content
        '400':
          description: Request body malformed.
        '404':
          description: Destination not found.
      description: Replace a destination configuration for a particular destination .
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/plugin-config'
  '/destinations/{destination-id}/testing':
    parameters:
      - schema:
          type: string
        name: destination-id
        in: path
        required: true
    post:
      summary: Test a destination
      tags: []
      operationId: post-destinations-destination-id-testing
      responses:
        '200':
          description: TODO return test outcome and log events.
      description: Test the connection to a particular destination.
  /kinds/source:
    get:
      summary: Get source kinds
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plugin-kind'
      operationId: get-kinds-source
      description: Retrieve the available kinds of sources.
  '/kinds/{kind-id}':
    parameters:
      - schema:
          type: string
        name: kind-id
        in: path
        required: true
    get:
      summary: Get plugin schema
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  schema:
                    $ref: '#/components/schemas/plugin-schema'
        '404':
          description: Kind not found.
      operationId: get-kinds-kind-id
      description: Get the configuration schema for a particular kind of source.
  /kinds/destination:
    get:
      summary: Get destination kinds
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/plugin-kind'
      operationId: get-kinds-destination
      description: Retrieve the available kinds of destinations.
components:
  schemas:
    plugin:
      description: A configured source.
      type: object
      x-examples:
        example-1:
          id: 0
          name: string
          kind: string
          version: string
          config:
            - name: string
              value: 0
      title: Source
      examples:
        - id: 0
          name: string
          kind: string
          version: string
          config:
            - name: string
              value: 0
      properties:
        id:
          type: number
          readOnly: true
        kind:
          type: string
          minLength: 1
        version:
          type: string
          minLength: 1
        config:
          $ref: '#/components/schemas/plugin-config'
      required:
        - id
        - kind
        - version
        - config
    plugin-config:
      description: ''
      x-examples:
        example-1:
          properties:
            a.config.field: 0
            another.config.field: 0
      examples:
        - {}
      type: object
      properties:
        a.config.field:
          $ref: '#/components/schemas/plugin-config-entry'
        another.config.field:
          $ref: '#/components/schemas/plugin-config-entry'
    plugin-schema:
      description: ''
      x-examples:
        example-1:
          properties:
            a.config.field: 0
            another.config.field: 0
      examples:
        - {}
      type: object
      properties:
        a.config.field:
          $ref: '#/components/schemas/plugin-schema-entry'
        another.config.field:
          $ref: '#/components/schemas/plugin-schema-entry'
    plugin-kind:
      description: ''
      type: object
      x-examples:
        example-1:
          kind: string
      properties:
        name:
          type: string
          minLength: 1
        id:
          type: string
      required:
        - name
    plugin-schema-entry:
      description: ''
      type: object
      properties:
        description:
          type: string
          minLength: 1
        sensitive:
          type: boolean
      required:
        - description
        - sensitive
      x-examples:
        example-1:
          description: string
          sensitive: true
    plugin-config-entry:
      description: ''
      type: object
      properties:
        value:
          type: string
          minLength: 1
      required:
        - value
      x-examples:
        example-1:
          value: string
  responses: {}
