openapi: 3.1.0
info:
  title: public-http-api
  version: '1.0'
  summary: The Precog public HTTP REST API.
  description: The Precog public HTTP REST API.
  contact:
    url: 'https://precog.com'
    email: support@precog.com
servers:
  - url: 'http://localhost:3000'
paths:
  /sources:
    get:
      summary: Get Sources
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/source'
      operationId: get-sources
      description: Retrieve the configured sources.
    post:
      summary: Create Source
      tags: []
      operationId: post-sources
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/source'
        '400':
          description: Request body malformed.
        '415':
          description: Source kind unsupported. <or> Source version unsupported.
      description: Configure a new source.
  '/sources/{source-id}':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    get:
      summary: Get a source
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/source'
        '404':
          description: Source not found.
      operationId: get-sources-source-id
      description: Get a particular source.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    post:
      summary: Replace a source config
      tags: []
      operationId: post-sources-source-id
      responses:
        '204':
          description: No Content
        '400':
          description: Request body malformed.
        '404':
          description: Source not found.
      description: Replace a source configuration for a particular source.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/source-config'
  '/sources/{source-id}/renaming':
    parameters:
      - schema:
          type: string
        name: source-id
        in: path
        required: true
    post:
      summary: Rename a source.
      tags: []
      operationId: post-sources-source-id-renaming
      responses:
        '204':
          description: No Content
        '400':
          description: Request body malformed.
        '404':
          description: Source not found.
      description: Rename a particular source.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                sourceName:
                  type: string
                  minLength: 1
              required:
                - sourceName
              x-examples:
                example-1:
                  sourceName: string
components:
  schemas:
    source:
      description: A configured source.
      type: object
      x-examples:
        example-1:
          id: 0
          name: string
          kind: string
          version: string
          config:
            - name: string
              value: 0
      title: Source
      examples:
        - id: 0
          name: string
          kind: string
          version: string
          config:
            - name: string
              value: 0
      properties:
        id:
          type: number
          readOnly: true
        name:
          type: string
          minLength: 1
        kind:
          type: string
          minLength: 1
        version:
          type: string
          minLength: 1
        config:
          type: array
          uniqueItems: true
          minItems: 0
          items:
            $ref: '#/components/schemas/source-config'
      required:
        - id
        - name
        - kind
        - version
        - config
    source-config:
      description: ''
      type: object
      x-examples:
        example-1:
          config:
            - name: string
              value: 0
      properties:
        config:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              name:
                type: string
                minLength: 1
              value:
                type:
                  - string
                  - number
                  - boolean
            required:
              - name
              - value
      required:
        - config
  responses: {}
